In [2]:
import torch
x = torch.empty(5,3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0829, 0.6251, 0.2412],
        [0.6000, 0.8902, 0.9586],
        [0.4284, 0.1075, 0.6150],
        [0.6919, 0.6896, 0.0630],
        [0.8000, 0.2963, 0.6550]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([23.43,423])
print(x)

tensor([ 23.4300, 423.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)  

tensor([[ 0.0941, -1.4042,  1.2119],
        [-0.3692,  0.1077,  0.5576],
        [ 2.0633, -0.8258, -0.3408],
        [ 1.9089, -1.3540,  0.8126],
        [-0.6684,  0.2932, -1.3654]])


In [9]:
print(x.size()) # torch.Size is in fact a tuple, so it supports all tuple operations.

torch.Size([5, 3])


In [12]:
# add
y = torch.rand(5, 3)
xysum = x+y
print(xysum)
xysum2 = torch.add(x, y)
print(xysum2)
print(xysum == xysum2)

tensor([[ 0.5120, -1.0304,  1.7752],
        [ 0.4975,  0.3669,  0.7348],
        [ 2.7388,  0.1668,  0.6240],
        [ 2.8995, -0.4529,  1.7543],
        [-0.5330,  0.3732, -0.6511]])
tensor([[ 0.5120, -1.0304,  1.7752],
        [ 0.4975,  0.3669,  0.7348],
        [ 2.7388,  0.1668,  0.6240],
        [ 2.8995, -0.4529,  1.7543],
        [-0.5330,  0.3732, -0.6511]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)


In [13]:
# providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5120, -1.0304,  1.7752],
        [ 0.4975,  0.3669,  0.7348],
        [ 2.7388,  0.1668,  0.6240],
        [ 2.8995, -0.4529,  1.7543],
        [-0.5330,  0.3732, -0.6511]])


In [14]:
# in-place
# Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x.
y.add_(x)
print(y)

tensor([[ 0.5120, -1.0304,  1.7752],
        [ 0.4975,  0.3669,  0.7348],
        [ 2.7388,  0.1668,  0.6240],
        [ 2.8995, -0.4529,  1.7543],
        [-0.5330,  0.3732, -0.6511]])


In [17]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0577])
1.0577144622802734


In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

a = np.ones(5)
b = torch.from_numpy(a)
# np.add(a, 1, out=a)
a = np.add(a, 1)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
